package world.gregs.voidps.cache.type

/**
 * Marker interface for data classes that can be serialized/deserialized.
 */
interface Type {
    fun component1(): Any? = null
    fun component2(): Any? = null
    fun component3(): Any? = null
    fun component4(): Any? = null
    fun component5(): Any? = null
    fun component6(): Any? = null
    fun component7(): Any? = null
    fun component8(): Any? = null
    fun component9(): Any? = null
    fun component10(): Any? = null
    fun component11(): Any? = null
    fun component12(): Any? = null
    fun component13(): Any? = null
    fun component14(): Any? = null
    fun component15(): Any? = null
    fun component16(): Any? = null
    fun component17(): Any? = null
    fun component18(): Any? = null
    fun component19(): Any? = null
    fun component20(): Any? = null
    fun component21(): Any? = null
    fun component22(): Any? = null
    fun component23(): Any? = null
    fun component24(): Any? = null
    fun component25(): Any? = null
    fun component26(): Any? = null
    fun component27(): Any? = null
    fun component28(): Any? = null
    fun component29(): Any? = null
    fun component30(): Any? = null
    fun component31(): Any? = null
    fun component32(): Any? = null
    fun component33(): Any? = null
    fun component34(): Any? = null
    fun component35(): Any? = null
    fun component36(): Any? = null
    fun component37(): Any? = null
    fun component38(): Any? = null
    fun component39(): Any? = null
    fun component40(): Any? = null
    fun component41(): Any? = null
    fun component42(): Any? = null
    fun component43(): Any? = null
    fun component44(): Any? = null
    fun component45(): Any? = null
    fun component46(): Any? = null
    fun component47(): Any? = null
    fun component48(): Any? = null
    fun component49(): Any? = null
    fun component50(): Any? = null
    fun component51(): Any? = null
    fun component52(): Any? = null
    fun component53(): Any? = null
    fun component54(): Any? = null
    fun component55(): Any? = null
    fun component56(): Any? = null
    fun component57(): Any? = null
    fun component58(): Any? = null
    fun component59(): Any? = null
    fun component60(): Any? = null
    fun component61(): Any? = null
    fun component62(): Any? = null
    fun component63(): Any? = null
    fun component64(): Any? = null
    fun component65(): Any? = null
    fun component66(): Any? = null
    fun component67(): Any? = null
    fun component68(): Any? = null
    fun component69(): Any? = null
    fun component70(): Any? = null
    fun component71(): Any? = null
    fun component72(): Any? = null
    fun component73(): Any? = null
    fun component74(): Any? = null
    fun component75(): Any? = null

    /**
     * Exposes componentN() methods (typically auto-generated by data classes)
     * To avoid needing to manually specify "load" methods in [TypeDecoder]s.
     * Example:
     * ```kotlin
     * fun load(type: TestType) {
     *     ID.set(type.id)
     *     NAME.set(type.name)
     *     SIZE.set(type.size)
     *     // etc...
     * }
     * ```
     */
    fun component(index: Int) = when (index) {
        0 -> component1()
        1 -> component2()
        2 -> component3()
        3 -> component4()
        4 -> component5()
        5 -> component6()
        6 -> component7()
        7 -> component8()
        8 -> component9()
        9 -> component10()
        10 -> component11()
        11 -> component12()
        12 -> component13()
        13 -> component14()
        14 -> component15()
        15 -> component16()
        16 -> component17()
        17 -> component18()
        18 -> component19()
        19 -> component20()
        20 -> component21()
        21 -> component22()
        22 -> component23()
        23 -> component24()
        24 -> component25()
        25 -> component26()
        26 -> component27()
        27 -> component28()
        28 -> component29()
        29 -> component30()
        30 -> component31()
        31 -> component32()
        32 -> component33()
        33 -> component34()
        34 -> component35()
        35 -> component36()
        36 -> component37()
        37 -> component38()
        38 -> component39()
        39 -> component40()
        40 -> component41()
        41 -> component42()
        42 -> component43()
        43 -> component44()
        44 -> component45()
        45 -> component46()
        46 -> component47()
        47 -> component48()
        48 -> component49()
        49 -> component50()
        50 -> component51()
        51 -> component52()
        52 -> component53()
        53 -> component54()
        54 -> component55()
        55 -> component56()
        56 -> component57()
        57 -> component58()
        58 -> component59()
        59 -> component60()
        60 -> component61()
        61 -> component62()
        62 -> component63()
        63 -> component64()
        64 -> component65()
        65 -> component66()
        66 -> component67()
        67 -> component68()
        68 -> component69()
        69 -> component70()
        70 -> component71()
        71 -> component72()
        72 -> component73()
        73 -> component74()
        74 -> component75()
        else -> throw IllegalArgumentException("Invalid type field index: $index. Are TypeDecoder fields in the same order as the Type object?")
    }
}