coverage:
  status:
    project:
      default:
        threshold: 10%
        informational: true # for viewing only to stop it failing builds
        if_not_found: success
        if_ci_failed: success
        flag_coverage_not_uploaded_behavior: pass
    patch:
      default:
        threshold: 10%
        informational: true
        if_not_found: success
        if_ci_failed: success
        flag_coverage_not_uploaded_behavior: pass
comment:
  layout: "condensed_header, files, diff, components"
  hide_project_coverage: false
  behavior: default
component_management:
  individual_components:
    - component_id: game_module
      name: Content
      paths:
        - game/
    - component_id: engine_module
      name: Engine
      paths:
        - engine/
    - component_id: network_module
      name: Network
      paths:
        - network/
github_checks:
  annotations: false