package world.gregs.voidps.world.interact.dialogue

sealed class Expression

object Talk : Expression()
object Talking : Expression()
object Laugh : Expression()
object Suspicious : Expression()
object Cheerful : Expression()
object RollEyes : Expression()
object Angry : Expression()
object Sad : Expression()
object Happy : Expression()
object Surprised : Expression()
object Uncertain : Expression()
object Unsure : Expression()
object Furious : Expression()
object Shock : Expression()
object Drunk : Expression()
object Asleep : Expression()
object Afraid : Expression()
object Upset : Expression()
object Amazed : Expression()
object Chuckle : Expression()
object EvilLaugh : Expression()

object OldSurprised : Expression()
object OldSad : Expression()
object OldAfraid : Expression()
object OldAngry : Expression()
object OldAsleep : Expression()
object OldTalking : Expression()
object OldUncertain : Expression()
object OldTalk : Expression()
object OldUnsure : Expression()
object OldRollEyes : Expression()
object OldSuspicious : Expression()
object OldCheerful : Expression()
object OldLaugh : Expression()