package world.gregs.voidps.world.interact.dialogue

sealed class Expression

object Talk : Expression()
object Talking : Expression()
object Laugh : Expression()
object Suspicious : Expression()
object Cheerful : Expression()
object RollEyes : Expression()
object Angry : Expression()
object Sad : Expression()
object Happy : Expression()
object Surprised : Expression()
object Uncertain : Expression()
object Unsure : Expression()
object Furious : Expression()
object Shock : Expression()
object Drunk : Expression()
object Asleep : Expression()
object Afraid : Expression()
object Upset : Expression()
object Amazed : Expression()
object Chuckle : Expression()
object EvilLaugh : Expression()

object SurprisedOld : Expression()
object SadOld : Expression()
object AfraidOld : Expression()
object AngryOld : Expression()
object AsleepOld : Expression()
object TalkingOld : Expression()
object UncertainOld : Expression()
object TalkOld : Expression()
object UnsureOld : Expression()
object RollEyesOld : Expression()
object SuspiciousOld : Expression()
object CheerfulOld : Expression()
object LaughOld : Expression()