package world.gregs.voidps.network.login

object Protocol {
    const val PLAYER_OPTION = 0
    const val INTERFACE_SPRITE = 75
    const val INTERFACE_COLOUR = 32
    const val INTERFACE_COMPONENT_SETTINGS = 34
    const val INTERFACE_REFRESH = 72
    const val INTERFACE_OPEN = 37
    const val NPC_UPDATING = 118
    const val INTERFACE_SCROLL_VERTICAL = 81
    const val INTERFACE_ITEM = 90
    const val OBJECT_PRE_FETCH = 79
    const val RUN_ENERGY = 4
    const val CLIENT_VARBIT = 73
    const val FLOOR_ITEM_REMOVE = 27
    const val INTERFACE_PLAYER_BODY = 114
    const val CLEAR_ZONE = 33
    const val INTERFACE_ANIMATION = 24
    const val OBJECT_ADD = 82
    const val TILE_TEXT = 46
    const val INTERFACE_TEXT = 10
    const val INTERFACE_ITEMS = 20
    const val CLIENT_VARP_LARGE = 44
    const val GRAPHIC_AREA = 84
    const val REGION = 19
    const val INTERFACE_CUSTOM_HEAD = 95
    const val OBJECT_REMOVE = 58
    const val UPDATE_ZONE = 41
    const val BATCH_UPDATE_ZONE = 48
    const val OBJECT_ANIMATION_SPECIFIC = 17
    const val FLOOR_ITEM_ADD = 63
    const val SCRIPT = 8
    const val LOGOUT = 55
    const val CLIENT_VARC_STR_LARGE = 53
    const val CLIENT_VARC_STR = 92
    const val INTERFACE_MODEL = 23
    const val FLOOR_ITEM_REVEAL = 109
    const val PROJECTILE_ADD = 15
    const val SOUND_EFFECT = 103
    const val MIDI_SOUND = 106
    const val PLAY_MUSIC = 85
    const val INTERFACE_WINDOW = 102
    const val PLAYER_UPDATING = 105
    const val INTERFACE_CLOSE = 112
    const val INTERFACE_ITEMS_UPDATE = 28
    const val FLOOR_ITEM_UPDATE = 71
    const val CLIENT_VARBIT_LARGE = 68
    const val PROJECTILE_DISPLACE = 51
    const val SKILL_LEVEL = 47
    const val OBJECT_ANIMATION = 29
    const val INTERFACE_NPC_HEAD = 86
    const val CLIENT_VARP = 7
    const val PLAYER_WEIGHT = 91
    const val GAME_MESSAGE = 52
    const val INTERFACE_COMPONENT_POSITION = 45
    const val INTERFACE_PLAYER_OTHER_BODY = 57
    const val CLIENT_VARC = 3
    const val CLIENT_VARC_LARGE = 16
    const val INTERFACE_PLAYER_HEAD = 77
    const val INTERFACE_COMPONENT_VISIBILITY = 108
    const val MIDI_AREA = 66
    const val SOUND_AREA = 5
    const val INTERFACE_COMPONENT_ORIENTATION = 88
    const val DYNAMIC_REGION = 70
    const val JINGLE = 116
    const val PUBLIC_CHAT = 38
    const val CLAN_CHAT = 65
    const val PRIVATE_CHAT_FROM = 78
    const val CLAN_QUICK_CHAT = 111
    const val UPDATE_FRIENDS = 36
    const val UNLOCK_IGNORES = 120
    const val UPDATE_IGNORE = 9
    const val UPDATE_CLAN_CHAT = 13
    const val APPEND_CLAN_CHAT = 31
    const val PUBLIC_STATUS = 83
    const val PRIVATE_STATUS = 113
    const val PRIVATE_QUICK_CHAT_FROM = 94
    const val PRIVATE_CHAT_TO = 61
    const val PRIVATE_QUICK_CHAT_TO = 99
    const val CAMERA_MOVE = 119
    const val CAMERA_TURN = 25
    const val CAMERA_SHAKE = 76
    const val CAMERA_RESET = 80
    const val MINIMAP_STATE = 104
    const val GRAND_EXCHANGE_SLOT = 101

    object Batch {
        const val FLOOR_ITEM_REMOVE = 0
        const val OBJECT_ADD = 1
        const val OBJECT_ANIMATION_SPECIFIC = 2
        const val OBJECT_REMOVE = 3
        const val FLOOR_ITEM_REVEAL = 4
        const val PROJECTILE_ADD = 5
        const val FLOOR_ITEM_ADD = 6
        const val FLOOR_ITEM_UPDATE = 7
        const val OBJECT_PRE_FETCH = 8
        const val PROJECTILE_DISPLACE = 9
        const val MIDI_AREA = 10
        const val SOUND_AREA = 11
        const val GRAPHIC_AREA = 12
        const val TILE_TEXT = 13
    }

    // Chat
    const val UNUSED_CHAT = 30
    const val UNUSED_QUICK_CHAT = 21

    const val UNKNOWN_2 = 8 // size -2
    const val UNKNOWN_3 = 50 // size -1
    const val UNKNOWN_4 = 18 // size 0
    const val UNKNOWN_5 = 40 // size -1
    const val UNKNOWN_7 = 39 // size 8
    const val UNKNOWN_11 = 60 // size 0
    const val UNKNOWN_14 = 92 // size -1
    const val WORLD_LIST_FULL = 98 // size -2
    const val UNKNOWN_16 = 12 // size 0
    const val UNKNOWN_19 = 49 // size 4
    const val UNKNOWN_20 = 69 // size 12
    const val UNKNOWN_21 = 64 // size 2
    const val UNKNOWN_22 = 115 // size 11
    const val UNKNOWN_23 = 26 // size 11
    const val UNKNOWN_24 = 89 // size 0
    const val UNKNOWN_25 = 43 // size 4
    const val UNKNOWN_26 = 6 // size 2
    const val UNKNOWN_27 = 56 // size 2
    const val UNKNOWN_28 = 63 // size 5
    const val UNKNOWN_29 = 93 // size -2
    const val UNKNOWN_30 = 59 // size 3
    const val UNKNOWN_31 = 1 // size 2
    const val UNKNOWN_32 = 55 // size 0
    const val UNKNOWN_33 = 110 // size 10
    const val UNKNOWN_34 = 74 // size 28
    const val UNKNOWN_35 = 11 // size 6
    const val UNKNOWN_36 = 107 // size 6
    const val UNKNOWN_37 = 23 // size 6
    const val UNKNOWN_38 = 2 // size 6
    const val UNKNOWN_39 = 87 // size 1
    const val UNKNOWN_40 = 67 // size 3
    const val UNKNOWN_41 = 14 // size 2
    const val UNKNOWN_48 = 97 // size 0
    const val UNKNOWN_49 = 62 // size 4
    const val UNKNOWN_52 = 22 // size 0
    const val UNKNOWN_54 = 96 // size 8
    const val UNKNOWN_55 = 117 // size 1
    const val UNKNOWN_56 = 35 // size 0
    const val UNKNOWN_57 = 100 // size -1
    const val UNKNOWN_59 = 53 // size -2
    const val UNKNOWN_62 = 54 // size 4
    const val UNKNOWN_64 = 42 // size -1
}
