package world.gregs.voidps.network.login

object Protocol {
    const val PLAYER_OPTION = 1
    const val INTERFACE_SPRITE = 2
    const val INTERFACE_COLOUR = 130
    const val INTERFACE_COMPONENT_SETTINGS = 3
    const val INTERFACE_REFRESH = 4
    const val INTERFACE_OPEN = 5
    const val NPC_UPDATING = 6
    const val INTERFACE_SCROLL_VERTICAL = 8
    const val INTERFACE_ITEM = 9
    const val OBJECT_PRE_FETCH = 11
    const val RUN_ENERGY = 13
    const val CLIENT_VARBIT = 14
    const val FLOOR_ITEM_REMOVE = 16
    const val INTERFACE_PLAYER_BODY = 18
    const val CLEAR_ZONE = 26
    const val INTERFACE_ANIMATION = 23
    const val OBJECT_ADD = 28
    const val TILE_TEXT = 32
    const val INTERFACE_TEXT = 33
    const val UPDATE_INV_FULL = 37
    const val CLIENT_VARP_LARGE = 39
    const val GRAPHIC_AREA = 108
    const val REGION = 43
    const val INTERFACE_CUSTOM_HEAD = 44
    const val OBJECT_REMOVE = 45
    const val UPDATE_ZONE = 46
    const val BATCH_UPDATE_ZONE = 87
    const val OBJECT_ANIMATION_SPECIFIC = 47
    const val FLOOR_ITEM_ADD = 48
    const val SCRIPT = 50
    const val LOGOUT = 51
    const val CLIENT_VARC_STR_LARGE = 140
    const val CLIENT_VARC_STR = 54
    const val INTERFACE_MODEL = 58
    const val FLOOR_ITEM_REVEAL = 60
    const val PROJECTILE_ADD = 62
    const val SOUND_EFFECT = 106
    const val MIDI_SOUND = 78
    const val PLAY_MUSIC = 31
    const val INTERFACE_WINDOW = 67
    const val PLAYER_UPDATING = 69
    const val INTERFACE_CLOSE = 73
    const val UPDATE_INV_PARTIAL = 80
    const val FLOOR_ITEM_UPDATE = 83
    const val CLIENT_VARBIT_LARGE = 84
    const val PROJECTILE_DISPLACE = 90
    const val SKILL_LEVEL = 93
    const val OBJECT_ANIMATION = 96
    const val INTERFACE_NPC_HEAD = 98
    const val CLIENT_VARP = 101
    const val PLAYER_WEIGHT = 103
    const val GAME_MESSAGE = 102
    const val INTERFACE_COMPONENT_POSITION = 104
    const val INTERFACE_PLAYER_OTHER_BODY = 109
    const val CLIENT_VARC = 111
    const val CLIENT_VARC_LARGE = 112
    const val INTERFACE_PLAYER_HEAD = 114
    const val INTERFACE_COMPONENT_VISIBILITY = 117
    const val MIDI_AREA = 65
    const val SOUND_AREA = 119
    const val INTERFACE_COMPONENT_ORIENTATION = 88 //
    const val DYNAMIC_REGION = 128
    const val JINGLE = 0
    const val PUBLIC_CHAT = 91
    const val CLAN_CHAT = 138
    const val PRIVATE_CHAT_FROM = 78 //
    const val CLAN_QUICK_CHAT = 111 //
    const val UPDATE_FRIENDS = 85
    const val UNLOCK_IGNORES = 57
    const val UPDATE_IGNORE = 105
    const val UPDATE_CLAN_CHAT = 12 //
    const val APPEND_CLAN_CHAT = 24 //
    const val PUBLIC_STATUS = 83 //
    const val PRIVATE_STATUS = 113 //
    const val PRIVATE_QUICK_CHAT_FROM = 42
    const val PRIVATE_CHAT_TO = 61 //
    const val PRIVATE_QUICK_CHAT_TO = 97
    const val CAMERA_MOVE = 29
    const val CAMERA_TURN = 127
    const val CAMERA_SHAKE = 34
    const val CAMERA_RESET = 10
    const val MINIMAP_STATE = 68

    object Batch {
        const val OBJECT_ADD = 0
        const val SOUND_AREA = 1
        // object customize 2
        const val OBJECT_ANIMATION_SPECIFIC = 3
        const val OBJECT_PRE_FETCH = 4
        const val FLOOR_ITEM_REMOVE = 5
        const val PROJECTILE_ADD = 6
        const val OBJECT_REMOVE = 7
        const val FLOOR_ITEM_UPDATE = 8
        const val TILE_TEXT = 9
        const val PROJECTILE_DISPLACE = 10
        const val MIDI_AREA = 11
        const val GRAPHIC_AREA = 12
        const val FLOOR_ITEM_REVEAL = 13
        const val FLOOR_ITEM_ADD = 14
    }
}