package content.entity.player.command

import com.github.michaelbull.logging.InlineLogger
import world.gregs.voidps.engine.data.Settings
import world.gregs.voidps.engine.data.configFiles
import world.gregs.voidps.engine.data.definition.ObjectDefinitions
import world.gregs.voidps.engine.entity.obj.GameObject
import world.gregs.voidps.engine.entity.obj.GameObjects
import world.gregs.voidps.engine.entity.obj.ObjectShape
import world.gregs.voidps.engine.entity.obj.loadObjectSpawns
import world.gregs.voidps.engine.entity.obj.readObjectSpawns
import world.gregs.voidps.type.Tile
import java.io.File

object SceneEditorPersist {
    private val logger = InlineLogger()
    private val lock = Any()

    data class Entry(
        val objectId: Int,
        val x: Int,
        val y: Int,
        val plane: Int,
        val rotation: Int,
        val shape: Int,
        val remove: Boolean,
    )

    fun place(objectId: Int, x: Int, y: Int, plane: Int, rotation: Int = 0, shape: Int = ObjectShape.CENTRE_PIECE_STRAIGHT): String = synchronized(lock) {
        val definition = ObjectDefinitions.getOrNull(objectId) ?: return "unknown object id $objectId"
        val entry = Entry(definition.id, x, y, plane, rotation and 3, shape, remove = false)
        update(entry)
        reload()
        "placed ${definition.stringId.ifBlank { definition.id.toString() }} @ $x,$y,$plane rot=${entry.rotation}"
    }

    fun remove(objectId: Int, x: Int, y: Int, plane: Int, rotation: Int = 0, shape: Int = ObjectShape.CENTRE_PIECE_STRAIGHT): String = synchronized(lock) {
        val tile = Tile(x, y, plane)
        val removed = removeLive(objectId, tile, shape, rotation and 3)
        update(Entry(objectId, x, y, plane, rotation and 3, shape, remove = true))
        reload()
        if (removed) {
            "removed $objectId @ $x,$y,$plane (collision cleared)"
        } else {
            "queued remove $objectId @ $x,$y,$plane (not in live map)"
        }
    }

    fun flush(): String = synchronized(lock) {
        val entries = readEntries()
        reload()
        logger.info { "scene editor reloaded ${entries.size} persisted changes" }
        "reloaded ${entries.size} scene-editor change(s) from ${file.name}"
    }

    fun status(): String = synchronized(lock) {
        val entries = readEntries()
        "stored=+${entries.count { !it.remove }}/-${entries.count { it.remove }}"
    }

    private fun update(entry: Entry) {
        val entries = readEntries().toMutableList()
        val index = entries.indexOfFirst { it.x == entry.x && it.y == entry.y && it.plane == entry.plane && it.shape == entry.shape }
        if (index == -1) {
            entries += entry
        } else {
            entries[index] = entry
        }
        writeToml(entries)
    }

    private fun reload() {
        loadObjectSpawns(configFiles().list(Settings["spawns.objects"]))
    }

    private fun removeLive(objectId: Int, tile: Tile, shape: Int, rotation: Int): Boolean {
        val byShape = GameObjects.getShape(tile, shape)
        if (byShape != null && byShape.intId == objectId) {
            GameObjects.remove(byShape, collision = true)
            return true
        }
        val byId = GameObjects.findOrNull(tile, objectId)
        if (byId != null) {
            GameObjects.remove(byId, collision = true)
            return true
        }
        val probe = GameObject(objectId, tile, shape, rotation)
        if (GameObjects.contains(probe)) {
            GameObjects.remove(probe, collision = true)
            return true
        }
        return false
    }

    private fun readEntries(): List<Entry> {
        if (!file.exists()) {
            return emptyList()
        }
        return readObjectSpawns(listOf(file.path)).mapNotNull { spawn ->
            val objectId = spawn.id.toIntOrNull() ?: ObjectDefinitions.getOrNull(spawn.id)?.id ?: return@mapNotNull null
            Entry(objectId, spawn.x, spawn.y, spawn.level, spawn.rotation and 3, spawn.type, spawn.remove)
        }
    }

    private fun writeToml(entries: List<Entry>) {
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("# Auto-generated by scene editor. Do not hand-edit.")
                appendLine("spawns = [")
                for (entry in entries.sortedWith(compareBy({ it.x }, { it.y }, { it.plane }, { it.shape }))) {
                    val id = ObjectDefinitions.getOrNull(entry.objectId)?.stringId?.takeIf { it.isNotBlank() }
                        ?: entry.objectId.toString()
                    append("    { id = \"").append(id).append("\", x = ").append(entry.x)
                        .append(", y = ").append(entry.y).append(", level = ").append(entry.plane)
                        .append(", type = ").append(entry.shape).append(", rotation = ").append(entry.rotation)
                    if (entry.remove) {
                        append(", remove = true")
                    }
                    appendLine(" },")
                }
                appendLine("]")
            },
        )
    }

    private val file: File
        get() = File(Settings["storage.data"], "area/scene/editor.obj-spawns.toml")
}
