package content.skill.summoning

/**
 * Random overhead lines a summoned familiar periodically shouts (every ~30s, driven by the
 * familiar timer in [SummoningTimers]). Sourced from the RuneScape Wiki transcript "Overhead
 * dialogue" sections (https://runescape.wiki/w/Transcript:<Name>#Overhead_dialogue).
 *
 * Keyed by familiar npc id; familiars without an entry (e.g. phoenix, the gorajo bloodrager/
 * stormbringer/hoardstalker/skinweaver/worldbearer/deathslinger lines) simply stay silent.
 */
val FAMILIAR_OVERHEAD: Map<String, List<String>> = mapOf(
    "spirit_wolf_familiar" to listOf("Grrrrr...", "Whuff-whuff!"),
    "dreadfowl_familiar" to listOf("Bwaaak!", "Bwuk bwuk!"),
    "vampire_bat_familiar" to listOf("Squeak!", "Squeak squeak!"),
    "spirit_terrorbird_familiar" to listOf("Scree screee!", "Screee!"),
    "granite_crab_familiar" to listOf("Chitter!", "Click click!"),
    "praying_mantis_familiar" to listOf("Chitter!", "Clack clack!"),
    "giant_ent_familiar" to listOf("Groooooan!", "Creeeeak!"),
    "spirit_cobra_familiar" to listOf("Hssssssss!", "Hsss!"),
    "spirit_dagannoth_familiar" to listOf("Raaaw!", "Grrrowl!"),
    "thorny_snail_familiar" to listOf("Slither!", "Sclurp!"),
    "beaver_familiar" to listOf("Gnawgnaw...", "Gnaw ..."),
    "karamthulhu_overlord_familiar" to listOf("(Bow down!)", "(Obey!)"),
    "hydra_familiar" to listOf("Rassssssp!", "Raaaaasp!"),
    "spirit_jelly_familiar" to listOf("Jiggle!", "Flobble!"),
    "bunyip_familiar" to listOf("Glorp glorp!", "Glorp!"),
    "war_tortoise_familiar" to listOf("Hsss..."),
    "fruit_bat_familiar" to listOf("Squeeeak!", "Squeee!"),
    "abyssal_parasite_familiar" to listOf("Schlorp!", "Gurgle"),
    "abyssal_lurker_familiar" to listOf("Craaaw!", "Screee!"),
    "unicorn_stallion_familiar" to listOf("Whinney!", "Neigh!"),
    "magpie_familiar" to listOf("Chirrup!", "Twitter!"),
    "stranger_plant_familiar" to listOf("Rustle!", "Snapsnap!"),
    "desert_wyrm_familiar" to listOf("Ssssss!", "Hssssss!"),
    "evil_turnip_familiar" to listOf("Graaah!", "Hur hur hur!"),
    "spirit_scorpion_familiar" to listOf("Clatter!", "Clack clack!"),
    "arctic_bear_familiar" to listOf("Unf!", "Graaaowl!"),
    "spirit_spider_familiar" to listOf("Clitterclatter!", "Click!"),
    "bloated_leech_familiar" to listOf("Gurgle!", "Schlurp!"),
    "spirit_kalphite_familiar" to listOf("Click click!", "Hsssss!"),
    "honey_badger_familiar" to listOf("Raaaaar!", "Grooowl!"),
    "albino_rat_familiar" to listOf("Squeee!", "Squeak squeak!"),
    "granite_lobster_familiar" to listOf("Grind!", "Clonk clonk!"),
    "macaw_familiar" to listOf("Braaak!", "Caw!"),
    "bronze_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "iron_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "steel_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "mithril_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "adamant_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "rune_minotaur_familiar" to listOf("Out of the way!", "Hey, no-horns!"),
    "smoke_devil_familiar" to listOf("Hoot!", "Honk!"),
    "bull_ant_familiar" to listOf("Click click!", "Click!"),
    "wolpertinger_familiar" to listOf("Mew!", "Raawr!"),
    "compost_mound_familiar" to listOf("Splutter!", "Schlorp!"),
    "pack_yak_familiar" to listOf("Barooo barooo!", "Barooo!"),
    "spirit_cockatrice_familiar" to listOf("Bwwwark bwwwark!", "Bwwwark!"),
    "spirit_guthatrice_familiar" to listOf("Caaaw caaaw!", "Caaaw!"),
    "spirit_saratrice_familiar" to listOf("Hoooot hoooot!", "Hoooot!"),
    "spirit_zamatrice_familiar" to listOf("Screeee screeee!", "Screeee!"),
    "spirit_pengatrice_familiar" to listOf("Awk awk!", "Awk!"),
    "spirit_coraxatrice_familiar" to listOf("Craaw craaw!", "Craaw!"),
    "spirit_vulatrice_familiar" to listOf("Scraaaaw scraaaaw!", "Scraaaaw!"),
    "barker_toad_familiar" to listOf("Braaaaap!", "Craaaaaaak!"),
    "ibis_familiar" to listOf("Chirp!", "Twitter!"),
    "swamp_titan_familiar" to listOf("Something smells clean...", "The power of stench compels you!"),
    "spirit_mosquito_familiar" to listOf("Bzzzzzzzzz!", "Whiiiiiine!"),
    "void_spinner_familiar" to listOf("Whiiiiiir!", "Whiiiir!"),
    "forge_regent_familiar" to listOf("Sizzle!", "Crackle!"),
    "spirit_larupia_familiar" to listOf("Hssssss!", "Ssssss!"),
    "geyser_titan_familiar" to listOf("Pah!", "Flee from me!"),
    "lava_titan_familiar" to listOf("Sacred flames...", "By my fire..."),
    "steel_titan_familiar" to listOf("Stand back!", "I Am Legend!"),
    "obsidian_golem_familiar" to listOf("Onward to glory!", "Stand back!"),
    "talon_beast_familiar" to listOf("Growwwl!", "Mrowl!"),
    "abyssal_titan_familiar" to listOf("Mwanu b'ruum!", "T'verah hoshay!"),
    "void_torcher_familiar" to listOf("Scree!", "Squaa!"),
    "giant_chinchompa_familiar" to listOf("Squeek!", "Squeek squeek!"),
    "fire_titan_familiar" to listOf("Come on and fight!", "Hey, tiny!"),
    "moss_titan_familiar" to listOf("Don't get me mad!", "Little soft humies!"),
    "ice_titan_familiar" to listOf("I'm melting!", "It's so warm here!"),
    "spirit_tz-kih_familiar" to listOf("Squee!", "Squee squee!"),
    "spirit_graahk_familiar" to listOf("Howl!", "Rowr!"),
    "spirit_kyatt_familiar" to listOf("Grrrrrr!", "Mrrrowl!"),
    "void_shifter_familiar" to listOf("Chitter!", "Scree!"),
    "pyrelord_familiar" to listOf("Whoosh!", "Crackle!"),
    "void_ravager_familiar" to listOf("Rarf!", "Grrrrr!"),
    "ravenous_locust_familiar" to listOf("Whiiiiiine!", "Click!"),
    "iron_titan_familiar" to listOf("Victory!", "Crush them!"),
    "meerkats_familiar" to listOf("Squeak squeak!", "Simples!"),
    "clay_familiar_class_1_familiar" to listOf("Rumble!", "Rumble, rumble!"),
    "clay_familiar_class_2_familiar" to listOf("Rumble!", "Rumble, rumble!"),
    "clay_familiar_class_3_familiar" to listOf("Rumble!", "Rumble, rumble!"),
    "clay_familiar_class_4_familiar" to listOf("Rumble!", "Rumble, rumble!"),
    "clay_familiar_class_5_familiar" to listOf("Rumble!", "Rumble, rumble!"),
)
