package content.skill.summoning.familiar

import content.entity.player.dialogue.Frustrated
import content.entity.player.dialogue.Happy
import content.entity.player.dialogue.type.npc
import content.entity.player.dialogue.type.player
import world.gregs.voidps.engine.Script
import world.gregs.voidps.type.random

class Stormbringer : Script {
    init {
        npcOperate("Interact", "*_stormbringer_familiar") {
            if (!this["talked_to_stormbringer", false]) {
                this["talked_to_stormbringer"] = true
                npc<Frustrated>("Little cub, I see you have questions for me.")
                return@npcOperate
            }
            when (random.nextInt(4)) {
                0 -> {
                    player<Happy>("How do you cast magic? You don't seem to carry any runes.")
                    npc<Frustrated>("So, how can I possibly form magic?")
                    player<Happy>("Yes, I guess.")
                    npc<Frustrated>("You are right, we have no runes, but some of us are born with currents of magic rippling over our bodies. Such is the power generated by a stormbringer that we render our mothers blind and infertile during childbirth.")
                    npc<Frustrated>("One day I hope to be a Blind Mother. They are highly esteemed and carried on the back of their own worldbearer.")
                }
                1 -> {
                    player<Happy>("How powerful is a stormbringer? Have you killed a dragon?")
                    npc<Frustrated>("A drah-gon? Is that like the triple-bellied wolflok?")
                    player<Happy>("Probably not. Twenty-feet high, firebreathing?")
                    npc<Frustrated>("Oh, it sounds much like! Seven heads? Large bellows on its sides, pumping out acid?")
                    player<Happy>("Bellows? No, definitely no bellows.")
                    npc<Frustrated>("Then it is a shame. The creatures on our plane sound far more dangerous.")
                }
                2 -> {
                    player<Happy>("How do you like it in Daemonheim?")
                    npc<Frustrated>("I like it very little. I grow tired of this place.")
                    player<Happy>("Then why don't you just leave? If you're so tired of floating about behind me, why don't you just go?")
                    npc<Frustrated>("Do not tempt me. You are like a tiny pup, nibbling and barking at my heel. I am here because the gorajos greatest duty is to hinder the one who created this place.")
                    npc<Frustrated>("We sense that great headway has been made; that we have dropped over a waterfall and risen, coughing and spluttering to the surface. Yet, there are many turns and falls ahead.")
                    npc<Frustrated>("I follow you because you have shown a remarkable habit of stumbling into trouble, young fawn. When that trouble comes, we shall push you aside and finish this.")
                    player<Happy>("Charming.")
                }
                3 -> {
                    player<Happy>("I don't have any more questions.")
                    npc<Frustrated>("That is a good thing. We must prepare for the next battle.")
                }
            }
        }
    }
}
