#!/usr/bin/env python3
"""
gen-ninja.py

Purpose:
  Generate `build.ninja` for the Makefile + `kotlinc` build, giving fast
  incremental rebuilds at the module level (rebuild only the changed module and
  downstream modules).

How it works:
  - Enumerates Kotlin sources/resources for each module under `<module>/src/main`.
  - Emits Ninja rules that call `tools/kotlinc-compile-module.sh` with the right
    module inputs, module-to-module jar deps, and the Maven classpath file.
  - Treats the generated `scripts.txt` as an input to the `game` module.
"""
from __future__ import annotations

import argparse
from pathlib import Path


def list_files(root: Path, patterns: list[str]) -> list[Path]:
    files: list[Path] = []
    for pattern in patterns:
        files.extend(root.rglob(pattern))
    return sorted([p for p in files if p.is_file()])


def main() -> int:
    repo = Path(__file__).resolve().parents[1]

    parser = argparse.ArgumentParser(description="Generate a build.ninja for make+kotlinc builds.")
    parser.add_argument("--build-root", required=True)
    parser.add_argument("--kotlin-home", required=True)
    parser.add_argument("--maven-cp", required=True)
    parser.add_argument("--scripts-txt", required=True)
    parser.add_argument("--kotlinc-java-opts", default="-Xmx6g -Xms512m")
    parser.add_argument("--kotlinc-flags", default="")
    parser.add_argument("--include-db", action="store_true")
    args = parser.parse_args()

    build_root = Path(args.build_root)
    if not build_root.is_absolute():
        build_root = repo / build_root
    build_root.mkdir(parents=True, exist_ok=True)

    kotlin_home = Path(args.kotlin_home)
    if not kotlin_home.is_absolute():
        kotlin_home = repo / kotlin_home

    maven_cp = Path(args.maven_cp)
    if not maven_cp.is_absolute():
        maven_cp = repo / maven_cp

    scripts_txt = Path(args.scripts_txt)
    if not scripts_txt.is_absolute():
        scripts_txt = repo / scripts_txt

    modules: list[str] = ["buffer", "types", "config", "cache", "network", "engine", "game"]
    if args.include_db:
        modules = ["buffer", "types", "config", "cache", "network", "engine", "database", "game"]

    deps: dict[str, list[str]] = {
        "buffer": [],
        "types": [],
        "config": [],
        "cache": ["buffer", "types"],
        "network": ["buffer", "cache"],
        "engine": ["buffer", "cache", "network", "types", "config"],
        "database": ["types", "engine"],
        "game": ["engine", "cache", "network", "types", "config"] + (["database"] if args.include_db else []),
    }

    ninja = []
    ninja.append("ninja_required_version = 1.3")
    ninja.append(f"builddir = {build_root.as_posix()}")
    ninja.append("")
    ninja.append(f"root = {repo.as_posix()}")
    ninja.append(f"kotlin_home = {kotlin_home.as_posix()}")
    ninja.append(f"maven_cp = {maven_cp.as_posix()}")
    ninja.append(f"scripts_txt = {scripts_txt.as_posix()}")
    ninja.append(f"kotlinc_java_opts = {args.kotlinc_java_opts}")
    ninja.append(f"kotlinc_flags = {args.kotlinc_flags}")
    ninja.append("")

    ninja.append("rule kotlinc_module")
    ninja.append(
        "  command = ROOT_DIR=$root MODULE=$module OUT_JAR=$out BUILD_ROOT=$builddir "
        "KOTLIN_HOME=$kotlin_home MAVEN_CP_FILE=$maven_cp SCRIPTS_TXT_FILE=$scripts_txt "
        "MODULE_DEPS_CP=\"$module_deps_cp\" KOTLINC_JAVA_OPTS=\"$kotlinc_java_opts\" EXTRA_KOTLINC_FLAGS=\"$kotlinc_flags\" "
        "bash $root/tools/kotlinc-compile-module.sh"
    )
    ninja.append("  description = kotlinc $module")
    ninja.append("")

    # Ensure scripts.txt is considered an input for :game (generated by make target kt-script-metadata).
    # We don't run the generator inside ninja to keep it simple and deterministic.

    for module in modules:
        out_jar = build_root / module / f"{module}.jar"

        src_root = repo / module / "src" / "main" / "kotlin"
        res_root = repo / module / "src" / "main" / "resources"
        inputs: list[Path] = []
        if src_root.exists():
            inputs += list_files(src_root, ["*.kt"])
        if res_root.exists():
            inputs += list_files(res_root, ["*"])
        if module == "game":
            inputs.append(scripts_txt)

        # Add module jar deps + maven cp file as build dependencies.
        dep_jars = [build_root / dep / f"{dep}.jar" for dep in deps.get(module, [])]
        all_inputs = [*dep_jars, maven_cp, *inputs]

        module_deps_cp = ":".join([p.as_posix() for p in dep_jars])
        ninja.append(f"build {out_jar.as_posix()}: kotlinc_module " + " ".join(p.as_posix() for p in all_inputs))
        ninja.append(f"  module = {module}")
        ninja.append(f"  module_deps_cp = {module_deps_cp}")
        ninja.append("")

    # Convenience phony targets
    game_jar = (build_root / "game" / "game.jar").as_posix()
    ninja.append(f"build game: phony {game_jar}")
    ninja.append(f"default game")
    ninja.append("")

    out = build_root / "build.ninja"
    out.write_text("\n".join(ninja) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
