name: Run Tests
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
env:
  CACHE_VERSION: 1.2.0
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ build ]
    timeout-minutes: 10
    steps:
      - name: Run all tests
        if: steps.check_secret.outputs.exists == 'true'
        run: ./gradlew test
      - name: Run unit tests
        if: steps.check_secret.outputs.exists != 'true'
        run: ./gradlew test -x :game:test
      - name: Upload coverage report to Codecov
        if: steps.check_secret.outputs.exists == 'true'
        uses: codecov/codecov-action@v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: GregHib/void